/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proffun_NativeSend */

extern "C"
JNIEXPORT void JNICALL Java_proffun_NativeSend_send
(JNIEnv *, jclass, jobject, jint);

